package com.example.teacherassistantai.service;

public enum SummaryMode {
    SUBSECTION_LEVEL2_FROM_CHUNKS,
    SUBSECTION_FROM_CHUNKS,
    SUBSECTION_FROM_LEVEL2_AND_DIRECT_CHUNKS,
    SECTION_FROM_SUBSECTIONS_AND_DIRECT_CHUNKS,
    SECTION_FROM_CHUNKS_FALLBACK,
    CHAPTER_FROM_ORIGINAL_SUMMARY,
    CHAPTER_FROM_SECTIONS,
    CHAPTER_FALLBACK,
    DOCUMENT_FROM_PARTS,
    DOCUMENT_FROM_CHAPTERS,
    DOCUMENT_FALLBACK,
    PART_FROM_CHAPTERS,
    PART_FALLBACK
}
