services:
  postgres:
    image:  pgvector/pgvector:0.8.2-pg16-trixie
    container_name: postgres-server
    restart: unless-stopped
    environment:
      POSTGRES_DB: ai_teaching_assistant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/01-init.sql
    ports:
      - "5433:5432"
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis-server
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]  # bật AOF để lưu bền
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
    networks:
      - backend

  minio:
    image: minio/minio:${MINIO_TAG}
    container_name: minio-server
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
      MINIO_KMS_SECRET_KEY: ${MINIO_KMS_SECRET_KEY}
      MINIO_KMS_AUTO_ENCRYPTION: "on"
    command: server /data --address ":9100" --console-address ":9101"
    volumes:
      - minio_data:/data
    ports:
      - "9100:9100"
      - "9101:9101"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  minio_data:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local
