-- we don't know how to generate root <with-no-name> (class Root) :(

create extension if not exists vector;

comment on database postgres is 'default administrative connection database';

-- Unknown how to generate base type type

alter type vector owner to postgres;

-- Unknown how to generate base type type

alter type halfvec owner to postgres;

-- Unknown how to generate base type type

alter type sparsevec owner to postgres;

create table role
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    name       varchar(255)
        constraint uk8sewwnpamngi6b1dwaa88askk
            unique
);

alter table role
    owner to postgres;

create table subjects
(
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp(6) not null,
    updated_at   timestamp(6) not null,
    active       boolean      not null,
    code         varchar(20)  not null
        constraint ukrg7x1lyii7kdyycw98d45vep5
            unique,
    description  text,
    name         varchar(100) not null
        constraint ukaodt3utnw0lsov4k9ta88dbpr
            unique,
    subject_type varchar(255) not null
        constraint subjects_subject_type_check
            check ((subject_type)::text = ANY
        ((ARRAY ['TEXT_BASED'::character varying, 'STEM'::character varying, 'OTHER'::character varying])::text[])),
    owner_id     bigint
);

alter table subjects
    owner to postgres;

create table users
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    avatar     varchar(255) not null,
    email      varchar(100) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    enabled    boolean,
    full_name  varchar(100) not null,
    password   varchar(255)
);

alter table users
    owner to postgres;

create table agent_logs
(
    id                  bigint generated by default as identity
        primary key,
    created_at          timestamp(6) not null,
    updated_at          timestamp(6) not null,
    agent_type          varchar(255) not null
        constraint agent_logs_agent_type_check
            check ((agent_type)::text = ANY
        ((ARRAY ['QUIZ_GENERATOR'::character varying, 'GRADER'::character varying, 'RAG_RETRIEVER'::character varying, 'SYSTEM_CHATBOT'::character varying, 'KNOWLEDGE_CHATBOT'::character varying])::text[])),
    error_message       text,
    input_summary       text,
    output_summary      text,
    processing_time_ms  bigint,
    related_entity_id   bigint,
    related_entity_type varchar(100),
    success             boolean      not null,
    tokens_used         integer,
    subject_id          bigint
        constraint fkertp7lvv3tesapsxoeqbb5bsr
            references subjects,
    triggered_by        bigint
        constraint fk6t8huqcmr5f56yykrkw0b6ped
            references users
);

alter table agent_logs
    owner to postgres;

create index idx_agent_log_type
    on agent_logs (agent_type);

create index idx_agent_log_entity
    on agent_logs (related_entity_type, related_entity_id);

create table chat_sessions
(
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp(6) not null,
    updated_at   timestamp(6) not null,
    active       boolean      not null,
    session_type varchar(255) not null
        constraint chat_sessions_session_type_check
            check ((session_type)::text = ANY
        ((ARRAY ['SYSTEM_SUPPORT'::character varying, 'KNOWLEDGE_QA'::character varying])::text[])),
    title        varchar(255),
    subject_id   bigint
        constraint fkg4oicyahoh3sc4k3xod7reom8
            references subjects,
    user_id      bigint       not null
        constraint fk82ky97glaomlmhjqae1d0esmy
            references users
);

alter table chat_sessions
    owner to postgres;

create table chat_messages
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6) not null,
    updated_at       timestamp(6) not null,
    agent_type       varchar(255)
        constraint chat_messages_agent_type_check
            check ((agent_type)::text = ANY
        ((ARRAY ['QUIZ_GENERATOR'::character varying, 'GRADER'::character varying, 'RAG_RETRIEVER'::character varying, 'SYSTEM_CHATBOT'::character varying, 'KNOWLEDGE_CHATBOT'::character varying])::text[])),
    content          text         not null,
    response_time_ms bigint,
    role             varchar(255) not null
        constraint chat_messages_role_check
            check ((role)::text = ANY
                   ((ARRAY ['USER'::character varying, 'ASSISTANT'::character varying, 'SYSTEM'::character varying])::text[])),
    tokens_used      integer,
    session_id       bigint       not null
        constraint fk3cpkdtwdxndrjhrx3gt9q5ux9
            references chat_sessions
);

alter table chat_messages
    owner to postgres;

create table documents
(
    id                      bigint generated by default as identity
        primary key,
    created_at              timestamp(6)                                          not null,
    updated_at              timestamp(6)                                          not null,
    description             text,
    file_size_bytes         bigint                                                not null,
    file_type               varchar(20)                                           not null,
    processing_error        text,
    status                  varchar(255) default 'UPLOADED'::character varying    not null
        constraint documents_status_check
            check ((status)::text = ANY
                   (ARRAY ['UPLOADED'::text, 'PARSING'::text, 'CHUNKING'::text, 'EMBEDDING'::text, 'SUMMARISING'::text, 'READY'::text, 'FAILED'::text])),
    title                   varchar(255)                                          not null,
    subject_id              bigint                                                not null
        constraint fkpby9dar20817f18ipuxmqf4x4
            references subjects,
    uploaded_by             bigint                                                not null
        constraint fk1ugacya4ssi0ilf8a9tjycgs6
            references users,
    original_object_key     varchar(500)                                          not null
        constraint uk_documents_original_object_key
            unique,
    markdown_object_key     varchar(500)
        constraint uk_documents_markdown_object_key
            unique,
    chunks_object_key       varchar(500)
        constraint uktep4xlu4e4w9wo6wxrtneotqe
            unique,
    hierarchy_object_key    varchar(500)
        constraint ukh5qah95isythjselvgvav35t9
            unique,
    enrichment_completed_at timestamp(6),
    enrichment_error        text,
    enrichment_started_at   timestamp(6),
    enrichment_status       varchar(30)  default 'NOT_STARTED'::character varying not null
        constraint documents_enrichment_status_check
            check ((enrichment_status)::text = ANY
                   ((ARRAY ['NOT_STARTED'::character varying, 'QUEUED'::character varying, 'RUNNING'::character varying, 'ENRICHED'::character varying, 'PARTIAL_FAILED'::character varying, 'FAILED'::character varying, 'SKIPPED'::character varying])::text[])),
    enrichment_retry_count  integer      default 0                                not null,
    constraint uk_documents_subject_id
        unique (subject_id)
);

alter table documents
    owner to postgres;

create table users_roles
(
    users_id bigint not null
        constraint fkml90kef4w2jy7oxyqv742tsfc
            references users,
    roles_id bigint not null
        constraint fk15d410tj6juko0sq9k4km60xq
            references role,
    primary key (users_id, roles_id)
);

alter table users_roles
    owner to postgres;

create table document_nodes
(
    id             bigserial
        primary key,
    document_id    bigint                              not null
        references documents
            on delete cascade,
    parent_id      bigint
        references document_nodes
            on delete cascade,
    subject_id     bigint                              not null,
    node_type      varchar(30)                         not null,
    level          integer                             not null,
    title          varchar(500),
    section_path   text,
    order_index    integer                             not null,
    page_from      integer,
    page_to        integer,
    content        text,
    metadata_jsonb jsonb     default '{}'::jsonb       not null,
    created_at     timestamp default CURRENT_TIMESTAMP not null,
    updated_at     timestamp default CURRENT_TIMESTAMP not null,
    node_key       varchar(100)                        not null,
    constraint uk_document_nodes_document_node_key
        unique (document_id, node_key)
);

alter table document_nodes
    owner to postgres;

create table document_chunks
(
    id             bigint generated by default as identity
        primary key,
    created_at     timestamp(6)                                  not null,
    updated_at     timestamp(6)                                  not null,
    chunk_index    integer                                       not null,
    content        text                                          not null,
    subject_id     bigint                                        not null,
    document_id    bigint                                        not null
        constraint fkks8knsiau23lcmv9mydqjmj84
            references documents,
    embedding      vector(1024),
    chunk_type     varchar(20) default 'TEXT'::character varying not null,
    token_count    integer,
    metadata_jsonb jsonb       default '{}'::jsonb               not null,
    node_id        bigint
                                                                 references document_nodes
                                                                     on delete set null,
    parent_node_id bigint
                                                                 references document_nodes
                                                                     on delete set null,
    section_path   text,
    page_from      integer,
    page_to        integer,
    source_order   integer,
    embed_text     text        default ''::text                  not null,
    constraint uk_document_chunk_doc_index
        unique (document_id, chunk_index)
);

comment on column document_chunks.embedding is 'DigitalOcean Qwen3 Embedding 0.6B vectors stored as vector(1024)';

comment on column document_chunks.embed_text is 'Text used to generate the embedding vector; body only, no breadcrumb prefix.';

alter table document_chunks
    owner to postgres;

create index idx_chunk_document
    on document_chunks (document_id);

create index idx_chunk_subject
    on document_chunks (subject_id);

create index idx_chunk_doc_chunkindex
    on document_chunks (document_id, chunk_index);

create index idx_chunk_metadata_jsonb_gin
    on document_chunks using gin (metadata_jsonb);

create index idx_document_chunks_subject_document
    on document_chunks (subject_id, document_id);

create index idx_chunk_node
    on document_chunks (node_id);

create index idx_chunk_parent_node
    on document_chunks (parent_node_id);

create index idx_chunk_subject_pages
    on document_chunks (subject_id, page_from, page_to);

create index idx_chunk_doc_source_order
    on document_chunks (document_id, source_order);

create index idx_chunk_embedding_hnsw
    on document_chunks using hnsw (embedding vector_cosine_ops)
    where (embedding IS NOT NULL);

create table message_source_chunks
(
    message_id bigint not null
        constraint fkfr62l7wuw6oou39oso5xk5upy
            references chat_messages,
    chunk_id   bigint not null
        constraint fk4344raec9j12305s5pvuuiovv
            references document_chunks
);

alter table message_source_chunks
    owner to postgres;

create index idx_document_node_document
    on document_nodes (document_id);

create index idx_document_node_parent
    on document_nodes (parent_id);

create index idx_document_node_subject
    on document_nodes (subject_id);

create index idx_document_node_doc_order
    on document_nodes (document_id, order_index);

create index idx_document_node_metadata_jsonb_gin
    on document_nodes using gin (metadata_jsonb);

create index idx_document_nodes_doc_parent_order
    on document_nodes (document_id, parent_id, order_index);

create table document_node_artifacts
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6) not null,
    updated_at       timestamp(6) not null,
    artifact_type    varchar(40)  not null
        constraint document_node_artifacts_artifact_type_check
            check ((artifact_type)::text = ANY
        ((ARRAY ['SUMMARY'::character varying, 'REVIEW_QUESTION_SET'::character varying])::text[])),
    content_jsonb    jsonb        not null,
    retrieval_text   text,
    retrieval_text_hash varchar(128),
    embedding        vector(1024),
    embedding_model  varchar(120),
    embedding_dimensions integer,
    error_message    text,
    model            varchar(120) not null,
    prompt_version   varchar(80)  not null,
    source_hash      varchar(128) not null,
    status           varchar(30)  not null
        constraint document_node_artifacts_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'RUNNING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'SKIPPED'::character varying, 'RATE_LIMITED'::character varying])::text[])),
    token_count      integer,
    document_id      bigint       not null
        constraint fkmwbl9u53bvcmjtv79rc6htx2g
            references documents
            on delete cascade,
    document_node_id bigint       not null
        constraint fk2xul4o04cyukx9xrekeda7uou
            references document_nodes
            on delete cascade,
    constraint uk_node_artifact_version
        unique (document_node_id, artifact_type, prompt_version, model, source_hash)
);

alter table document_node_artifacts
    owner to postgres;

comment on column document_node_artifacts.retrieval_text is
    'Text used to generate the coarse retrieval embedding for this artifact.';

comment on column document_node_artifacts.retrieval_text_hash is
    'Hash of retrieval_text used to skip unchanged artifact embedding work.';

comment on column document_node_artifacts.embedding is
    'Coarse retrieval embedding generated from retrieval_text.';

comment on column document_node_artifacts.embedding_model is
    'Embedding model used for artifact coarse retrieval embedding.';

comment on column document_node_artifacts.embedding_dimensions is
    'Embedding vector dimension used for artifact coarse retrieval embedding.';

create index idx_node_artifacts_document_type_status
    on document_node_artifacts (document_id, artifact_type, status);

create index idx_node_artifacts_node_type
    on document_node_artifacts (document_node_id, artifact_type);

create index idx_node_artifacts_embedding_hnsw
    on document_node_artifacts using hnsw (embedding vector_cosine_ops)
    where (embedding IS NOT NULL);

create index idx_node_artifacts_embedding_model
    on document_node_artifacts (embedding_model, embedding_dimensions)
    where (embedding IS NOT NULL);
