create table role
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    name       varchar(255)
        constraint uk8sewwnpamngi6b1dwaa88askk
            unique
);

alter table role
    owner to postgres;

create table subjects
(
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp(6) not null,
    updated_at   timestamp(6) not null,
    active       boolean      not null,
    code         varchar(20)  not null
        constraint ukrg7x1lyii7kdyycw98d45vep5
            unique,
    description  text,
    name         varchar(100) not null
        constraint ukaodt3utnw0lsov4k9ta88dbpr
            unique,
    subject_type varchar(255) not null
        constraint subjects_subject_type_check
            check ((subject_type)::text = ANY
        ((ARRAY ['TEXT_BASED'::character varying, 'STEM'::character varying, 'OTHER'::character varying])::text[])),
    owner_id     bigint
);

alter table subjects
    owner to postgres;

create table users
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    avatar     varchar(255) not null,
    email      varchar(100) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    enabled    boolean,
    full_name  varchar(100) not null,
    password   varchar(255)
);

alter table users
    owner to postgres;

create table agent_logs
(
    id                  bigint generated by default as identity
        primary key,
    created_at          timestamp(6) not null,
    updated_at          timestamp(6) not null,
    agent_type          varchar(255) not null
        constraint agent_logs_agent_type_check
            check ((agent_type)::text = ANY
        ((ARRAY ['QUIZ_GENERATOR'::character varying, 'GRADER'::character varying, 'RAG_RETRIEVER'::character varying, 'SYSTEM_CHATBOT'::character varying, 'KNOWLEDGE_CHATBOT'::character varying])::text[])),
    error_message       text,
    input_summary       text,
    output_summary      text,
    processing_time_ms  bigint,
    related_entity_id   bigint,
    related_entity_type varchar(100),
    success             boolean      not null,
    tokens_used         integer,
    subject_id          bigint
        constraint fkertp7lvv3tesapsxoeqbb5bsr
            references subjects,
    triggered_by        bigint
        constraint fk6t8huqcmr5f56yykrkw0b6ped
            references users
);

alter table agent_logs
    owner to postgres;

create index idx_agent_log_type
    on agent_logs (agent_type);

create index idx_agent_log_entity
    on agent_logs (related_entity_type, related_entity_id);

create table classrooms
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6) not null,
    updated_at    timestamp(6) not null,
    academic_year varchar(20)  not null,
    active        boolean      not null,
    code          varchar(20),
    description   text,
    name          varchar(100) not null,
    semester      varchar(20),
    subject_id    bigint       not null
        constraint fk7wfw4q3ucaoiemigp6pk4vuvv
            references subjects,
    teacher_id    bigint       not null
        constraint fka9yroaq9q8bkmi9o7vjt66qkk
            references users
);

alter table classrooms
    owner to postgres;

create table chat_sessions
(
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp(6) not null,
    updated_at   timestamp(6) not null,
    active       boolean      not null,
    session_type varchar(255) not null
        constraint chat_sessions_session_type_check
            check ((session_type)::text = ANY
        ((ARRAY ['SYSTEM_SUPPORT'::character varying, 'KNOWLEDGE_QA'::character varying])::text[])),
    title        varchar(255),
    classroom_id bigint
        constraint fknj9v0hk68h89gcccjjhsgtfc9
            references classrooms,
    subject_id   bigint
        constraint fkg4oicyahoh3sc4k3xod7reom8
            references subjects,
    user_id      bigint       not null
        constraint fk82ky97glaomlmhjqae1d0esmy
            references users
);

alter table chat_sessions
    owner to postgres;

create table chat_messages
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6) not null,
    updated_at       timestamp(6) not null,
    agent_type       varchar(255)
        constraint chat_messages_agent_type_check
            check ((agent_type)::text = ANY
        ((ARRAY ['QUIZ_GENERATOR'::character varying, 'GRADER'::character varying, 'RAG_RETRIEVER'::character varying, 'SYSTEM_CHATBOT'::character varying, 'KNOWLEDGE_CHATBOT'::character varying])::text[])),
    content          text         not null,
    response_time_ms bigint,
    role             varchar(255) not null
        constraint chat_messages_role_check
            check ((role)::text = ANY
                   ((ARRAY ['USER'::character varying, 'ASSISTANT'::character varying, 'SYSTEM'::character varying])::text[])),
    tokens_used      integer,
    session_id       bigint       not null
        constraint fk3cpkdtwdxndrjhrx3gt9q5ux9
            references chat_sessions
);

alter table chat_messages
    owner to postgres;

create table documents
(
    id                   bigint generated by default as identity
        primary key,
    created_at           timestamp(6)                                       not null,
    updated_at           timestamp(6)                                       not null,
    description          text,
    file_size_bytes      bigint                                             not null,
    file_type            varchar(20)                                        not null,
    processing_error     text,
    status               varchar(255) default 'UPLOADED'::character varying not null
        constraint documents_status_check
            check ((status)::text = ANY
                   ((ARRAY ['UPLOADED'::character varying, 'PARSING'::character varying, 'CHUNKING'::character varying, 'EMBEDDING'::character varying, 'SUMMARISING'::character varying, 'READY'::character varying, 'FAILED'::character varying])::text[])),
    enrichment_status    varchar(30)  default 'NOT_STARTED'::character varying not null,
    enrichment_started_at timestamp(6),
    enrichment_completed_at timestamp(6),
    enrichment_error     text,
    enrichment_retry_count INTEGER NOT NULL DEFAULT 0,
    title                varchar(255)                                       not null,
    classroom_id         bigint
        constraint fk7aiojwtxhjitwsuhj7exotvne
            references classrooms,
    subject_id           bigint                                             not null
        constraint fkpby9dar20817f18ipuxmqf4x4
            references subjects,
    uploaded_by          bigint                                             not null
        constraint fk1ugacya4ssi0ilf8a9tjycgs6
            references users,
    original_object_key  varchar(500)                                       not null
        constraint uk_documents_original_object_key
            unique,
    markdown_object_key  varchar(500)
        constraint uk_documents_markdown_object_key
            unique,
    hierarchy_object_key varchar(500)
        constraint uk_documents_hierarchy_object_key
            unique,
    chunks_object_key    varchar(500)
        constraint uk_documents_chunks_object_key
            unique
);

alter table documents
    owner to postgres;

create table exams
(
    id                bigint generated by default as identity
        primary key,
    created_at        timestamp(6)     not null,
    updated_at        timestamp(6)     not null,
    description       text,
    duration_minutes  integer          not null,
    end_time          timestamp(6)     not null,
    passing_score     double precision not null,
    shuffle_options   boolean          not null,
    shuffle_questions boolean          not null,
    start_time        timestamp(6)     not null,
    status            varchar(255)     not null
        constraint exams_status_check
            check ((status)::text = ANY
        ((ARRAY ['DRAFT'::character varying, 'SCHEDULED'::character varying, 'ONGOING'::character varying, 'FINISHED'::character varying, 'CANCELLED'::character varying])::text[])),
    title             varchar(255)     not null,
    total_score       double precision not null,
    classroom_id      bigint           not null
        constraint fk3gdrl267p4meyvb9f8lf2ld21
            references classrooms,
    created_by        bigint           not null
        constraint fka9pp7fvh0i6302peis1x76ots
            references users
);

alter table exams
    owner to postgres;

create table exam_submissions
(
    id              bigint generated by default as identity
        primary key,
    created_at      timestamp(6) not null,
    updated_at      timestamp(6) not null,
    graded_at       timestamp(6),
    started_at      timestamp(6),
    status          varchar(255) not null
        constraint exam_submissions_status_check
            check ((status)::text = ANY
        ((ARRAY ['IN_PROGRESS'::character varying, 'SUBMITTED'::character varying, 'AI_GRADED'::character varying, 'TEACHER_REVIEWED'::character varying])::text[])),
    submitted_at    timestamp(6),
    teacher_comment text,
    total_score     double precision,
    exam_id         bigint       not null
        constraint fk3vnq59u82d1f5advlfpw14q2b
            references exams,
    graded_by       bigint
        constraint fk9dsxu68sadsr7qj4pk84m7f7i
            references users,
    student_id      bigint       not null
        constraint fk6u0rkv8ulm7w7xt7njokkoms6
            references users,
    constraint ukbbl161lhoispxt052w1b498bq
        unique (exam_id, student_id)
);

alter table exam_submissions
    owner to postgres;

create table question_banks
(
    id                 bigint generated by default as identity
        primary key,
    created_at         timestamp(6) not null,
    updated_at         timestamp(6) not null,
    description        text,
    published          boolean      not null,
    title              varchar(255) not null,
    created_by         bigint       not null
        constraint fkaoc8pganxt0sge51oqvc5oqcp
            references users,
    source_document_id bigint
        constraint fkm3ns1hqnogvq3g7438nlccu5x
            references documents,
    subject_id         bigint       not null
        constraint fkq4e6ileri8n8m82o7tlyfhxly
            references subjects
);

alter table question_banks
    owner to postgres;

create table questions
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6) not null,
    updated_at       timestamp(6) not null,
    content          text         not null,
    difficulty_level varchar(255) not null
        constraint questions_difficulty_level_check
            check ((difficulty_level)::text = ANY
        ((ARRAY ['EASY'::character varying, 'MEDIUM'::character varying, 'HARD'::character varying])::text[])),
    explanation      text,
    is_ai_generated  boolean      not null,
    question_type    varchar(255) not null
        constraint questions_question_type_check
            check ((question_type)::text = ANY
                   ((ARRAY ['MULTIPLE_CHOICE'::character varying, 'MULTI_SELECT'::character varying, 'TRUE_FALSE'::character varying, 'SHORT_ANSWER'::character varying, 'ESSAY'::character varying, 'FILL_IN_BLANK'::character varying])::text[])),
    source_chunk_id  bigint,
    tags             text,
    question_bank_id bigint       not null
        constraint fka2j9n3kb9yf3bej743fxio5c3
            references question_banks
);

alter table questions
    owner to postgres;

create table answer_options
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) not null,
    updated_at  timestamp(6) not null,
    content     text         not null,
    is_correct  boolean      not null,
    order_index integer,
    question_id bigint       not null
        constraint fkfapodm8kfiu9a9a4o2r43rcgp
            references questions
);

alter table answer_options
    owner to postgres;

create table exam_questions
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6)     not null,
    updated_at  timestamp(6)     not null,
    order_index integer          not null,
    score       double precision not null,
    exam_id     bigint           not null
        constraint fk5cd6sjmccb11rrwpyabyc81c0
            references exams,
    question_id bigint           not null
        constraint fks0t1710in6q97whp93ggrs1wg
            references questions,
    constraint uk1c2vckggluxw60j4oxa9d3k74
        unique (exam_id, question_id)
);

alter table exam_questions
    owner to postgres;

create table student_answers
(
    id                  bigint generated by default as identity
        primary key,
    created_at          timestamp(6) not null,
    updated_at          timestamp(6) not null,
    ai_feedback         text,
    answer_content      text,
    grading_status      varchar(255) not null
        constraint student_answers_grading_status_check
            check ((grading_status)::text = ANY
        ((ARRAY ['PENDING'::character varying, 'AUTO_GRADED'::character varying, 'AI_GRADED'::character varying, 'TEACHER_REVIEWED'::character varying])::text[])),
    score               double precision,
    selected_option_ids text,
    teacher_feedback    text,
    exam_question_id    bigint       not null
        constraint fkmqi0dhucfpcfbgnxy64v4ih4v
            references exam_questions,
    selected_option_id  bigint
        constraint fkh8ki2dt0w5xe2yntbcurb4ivr
            references answer_options,
    submission_id       bigint       not null
        constraint fkmwyg0ae81n40wynjmcthdndjv
            references exam_submissions
);

alter table student_answers
    owner to postgres;

create table user_classroom
(
    classroom_id bigint not null
        constraint fkheylf7gfmyq5i7cojra0tdfiu
            references classrooms,
    user_id      bigint not null
        constraint fk1qbkig495swro8tlj0iflw0ah
            references users,
    primary key (classroom_id, user_id)
);

alter table user_classroom
    owner to postgres;

create table users_roles
(
    users_id bigint not null
        constraint fkml90kef4w2jy7oxyqv742tsfc
            references users,
    roles_id bigint not null
        constraint fk15d410tj6juko0sq9k4km60xq
            references role,
    primary key (users_id, roles_id)
);

alter table users_roles
    owner to postgres;

create table document_nodes
(
    id             bigserial
        primary key,
    document_id    bigint                              not null
        references documents
            on delete cascade,
    parent_id      bigint
        references document_nodes
            on delete cascade,
    subject_id     bigint                              not null,
    node_key       varchar(100)                        not null,
    node_type      varchar(30)                         not null,
    level          integer                             not null,
    title          varchar(500),
    section_path   text,
    order_index    integer                             not null,
    page_from      integer,
    page_to        integer,
    content        text,
    metadata_jsonb jsonb     default '{}'::jsonb       not null,
    created_at     timestamp default CURRENT_TIMESTAMP not null,
    updated_at     timestamp default CURRENT_TIMESTAMP not null
);

alter table document_nodes
    owner to postgres;

create table document_chunks
(
    id             bigint generated by default as identity
        primary key,
    created_at     timestamp(6)                                  not null,
    updated_at     timestamp(6)                                  not null,
    chunk_index    integer                                       not null,
    content        text                                          not null,
    subject_id     bigint                                        not null,
    document_id    bigint                                        not null
        constraint fkks8knsiau23lcmv9mydqjmj84
            references documents,
    embedding      vector(1024),
    chunk_type     varchar(20) default 'TEXT'::character varying not null,
    token_count    integer,
    metadata_jsonb jsonb       default '{}'::jsonb               not null,
    node_id        bigint
                                                                 references document_nodes
                                                                     on delete set null,
    parent_node_id bigint
                                                                 references document_nodes
                                                                     on delete set null,
    section_path   text,
    page_from      integer,
    page_to        integer,
    source_order   integer,
    constraint uk_document_chunk_doc_index
        unique (document_id, chunk_index)
);

comment on column document_chunks.embedding is 'DigitalOcean Qwen3 Embedding 0.6B vectors stored as vector(1024)';

alter table document_chunks
    owner to postgres;

create index idx_chunk_document
    on document_chunks (document_id);

create index idx_chunk_subject
    on document_chunks (subject_id);

create index idx_chunk_doc_chunkindex
    on document_chunks (document_id, chunk_index);

create index idx_chunk_metadata_jsonb_gin
    on document_chunks using gin (metadata_jsonb);

create index idx_document_chunks_subject_document
    on document_chunks (subject_id, document_id);

create index idx_chunk_embedding_hnsw
    on document_chunks using hnsw (embedding vector_cosine_ops)
    where (embedding IS NOT NULL);

create index idx_chunk_node
    on document_chunks (node_id);

create index idx_chunk_parent_node
    on document_chunks (parent_node_id);

create index idx_chunk_subject_pages
    on document_chunks (subject_id, page_from, page_to);

create index idx_chunk_doc_source_order
    on document_chunks (document_id, source_order);

create table document_node_artifacts
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6)                           not null,
    updated_at       timestamp(6)                           not null,
    document_id      bigint                                 not null
        references documents
            on delete cascade,
    document_node_id bigint                                 not null
        references document_nodes
            on delete cascade,
    artifact_type    varchar(40)                            not null,
    status           varchar(30)                            not null,
    prompt_version   varchar(80)                            not null,
    model            varchar(120)                           not null,
    source_hash      varchar(128)                           not null,
    content_jsonb    jsonb default '{}'::jsonb              not null,
    error_message    text,
    token_count      integer,
    constraint uk_node_artifact_version
        unique (document_node_id, artifact_type, prompt_version, model, source_hash)
);

alter table document_node_artifacts
    owner to postgres;

create index idx_node_artifacts_document_type_status
    on document_node_artifacts (document_id, artifact_type, status);

create index idx_node_artifacts_node_type
    on document_node_artifacts (document_node_id, artifact_type);

create index idx_node_artifacts_content_gin
    on document_node_artifacts using gin (content_jsonb);

create table message_source_chunks
(
    message_id bigint not null
        constraint fkfr62l7wuw6oou39oso5xk5upy
            references chat_messages,
    chunk_id   bigint not null
        constraint fk4344raec9j12305s5pvuuiovv
            references document_chunks
);

alter table message_source_chunks
    owner to postgres;

create index idx_document_node_document
    on document_nodes (document_id);

create index idx_document_node_parent
    on document_nodes (parent_id);

create index idx_document_node_subject
    on document_nodes (subject_id);

create index idx_document_node_doc_order
    on document_nodes (document_id, order_index);

create unique index uk_document_nodes_document_node_key
    on document_nodes (document_id, node_key);

create index idx_document_nodes_doc_parent_order
    on document_nodes (document_id, parent_id, order_index);

create index idx_document_node_metadata_jsonb_gin
    on document_nodes using gin (metadata_jsonb);

-- Phase 2a migration: add SUMMARISING status, remove FULL_USE
ALTER TABLE documents DROP CONSTRAINT IF EXISTS documents_status_check;
ALTER TABLE documents ADD CONSTRAINT documents_status_check CHECK ((status)::text = ANY ((ARRAY ['UPLOADED'::character varying, 'PARSING'::character varying, 'CHUNKING'::character varying, 'EMBEDDING'::character varying, 'SUMMARISING'::character varying, 'READY'::character varying, 'FAILED'::character varying])::text[]));
UPDATE documents SET status = 'READY' WHERE status = 'FULL_USE';
